export const CREATE_PAPER = "CREATE_PAPER";
export const CREATE_PAPER_ERROR = "CREATE_PAPER_ERROR";
export const CLOSE_PAPER = "CLOSE_PAPER";
export const SUBMIT_PAPER = "SUBMIT_PAPER";
export const SUBMIT_ERROR = "SUBMIT_ERROR";
export const LOADING_PAPER = "LOADING_PAPER";
